language: cpp

install:
  - pip3 install conan

  # Fail if we can't run Conan.
  - conan --version



jobs:
    include:
        - os: linux
          dist: focal
          compiler: gcc

          addons:
              apt:
                  packages:
                      - python3
                      - python3-pip
          script:
            - mkdir build
            - cd build
            - cmake ..
            - make 
            - bin/unit-tests
    include:
        - os: linux
          dist: focal
          compiler: avr-gcc

          addons:
              apt:
                  packages:
                      - gcc-avr
          script:
            - mkdir build
            - cd build
            - cmake .. -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchain-avr-gcc.cmake
            - make 
